name: .NET Core Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish the application
      run: dotnet publish WindowsDuo.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WindowsDuo-App
        path: ./publish/
